export const levels = [
    { id: 0, level: "aprendiz" },
    { id: 1, level: "hobbista" },
    { id: 2, level: "freelancer" },
    { id: 3, level: "profissional" },
];

export const cardData = [
    {
        id: 0,
        img: "",
        title: "Homepage de ecommerce",
        user: "@carlos8v",
        desc: "Criação de um hotsite para divulgação de produtos de um ecommerce",
        stars: 315,
        likes: 67,
        level: 0,
    },
    {
        id: 1,
        img: "",
        title: "Templates de emails profissionais",
        user: "@marcelaf",
        desc: "Estilização de emails promocionais de empresas. Modelos: boas vindas, des Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        stars: 278,
        likes: 39,
        level: 0,
    },
    {
        id: 2,
        img: "",
        title: "Backend de biblioteca",
        user: "@tsnery",
        desc: "Aplicação com nodejs onde se tem CRUD de locação de livros de uma biblioteca Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        stars: 122,
        likes: 13,
        level: 1,
    },
    {
        id: 2,
        img: "",
        title: "Backend de biblioteca",
        user: "@tsnery",
        desc: "Aplicação com nodejs onde se tem CRUD de locação de livros de uma biblioteca Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        stars: 122,
        likes: 13,
        level: 1,
    },
    {
        id: 3,
        img: "",
        title: "",
        user: "",
        desc: "",
        stars: 0,
        likes: 0,
        level: 0,
    },
    {
        id: 4,
        img: "",
        title: "",
        user: "",
        desc: "",
        stars: 0,
        likes: 0,
        level: 0,
    },
    {
        id: 5,
        img: "",
        title: "",
        user: "",
        desc: "",
        stars: 0,
        likes: 0,
        level: 0,
    },
];
