export const levels = [
    { id: 0, level: "aprendiz" },
    { id: 1, level: "hobbista" },
    { id: 2, level: "freelancer" },
    { id: 3, level: "profissional" },
];

export const cardData = [
    {
        id: 0,
        img: "",
        title: "Homepage de ecommerce",
        user: "@carlos8v",
        desc: "Criação de um hotsite para divulgação de produtos de um ecommerce",
        stars: 315,
        likes: 67,
        level: "aprendiz",
    },
    {
        id: 1,
        img: "",
        title: "Templates de emails profissionais",
        user: "@marcelaf",
        desc: "Estilização de emails promocionais de empresas. Modelos: boas vindas, des Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        stars: 278,
        likes: 39,
        level: "aprendiz",
    },
    {
        id: 2,
        img: "",
        title: "Backend de biblioteca",
        user: "@tsnery",
        desc: "Aplicação com nodejs onde se tem CRUD de locação de livros de uma biblioteca Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        stars: 122,
        likes: 13,
        level: "hobbista",
    },
    {
        id: 3,
        img: "",
        title: "Title title title",
        user: "@user",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend est et purus finibus vehicula sit amet id arcu. In at ligula vel ligula lacinia rhoncus at at leo. Integer nibh dolor, dignissim non tempus quis, venenatis quis dui. Donec interdum faucibus lorem nec sagittis. Morbi auctor nec sem nec laoreet. Nam vitae massa nisi. Quisque vitae auctor augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in egestas ex, sit amet accumsan ante. Vivamus sed ultricies diam.",
        stars: 0,
        likes: 0,
        level: "aprendiz",
    },
    {
        id: 4,
        img: "",
        title: "Title title title",
        user: "@user",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend est et purus finibus vehicula sit amet id arcu. In at ligula vel ligula lacinia rhoncus at at leo. Integer nibh dolor, dignissim non tempus quis, venenatis quis dui. Donec interdum faucibus lorem nec sagittis. Morbi auctor nec sem nec laoreet. Nam vitae massa nisi. Quisque vitae auctor augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in egestas ex, sit amet accumsan ante. Vivamus sed ultricies diam.",
        stars: 0,
        likes: 0,
        level: "aprendiz",
    },
    {
        id: 5,
        img: "",
        title: "Title title title",
        user: "@user",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend est et purus finibus vehicula sit amet id arcu. In at ligula vel ligula lacinia rhoncus at at leo. Integer nibh dolor, dignissim non tempus quis, venenatis quis dui. Donec interdum faucibus lorem nec sagittis. Morbi auctor nec sem nec laoreet. Nam vitae massa nisi. Quisque vitae auctor augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in egestas ex, sit amet accumsan ante. Vivamus sed ultricies diam.",
        stars: 0,
        likes: 0,
        level: "aprendiz",
    },
];
